name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version information
      id: version_info
      run: |
        if [ "${{ github.event_name }}" == "push" ] && [ -n "${{ github.ref_type }}" ] && [ "${{ github.ref_type }}" == "tag" ]; then
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
        else
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "TAG_NAME=commit-${SHORT_SHA}" >> $GITHUB_ENV
          echo "VERSION=${SHORT_SHA}" >> $GITHUB_ENV
        fi

    - name: Build Docker Image
      run: |
        docker build -t jsfrnc/devops-toolbox:${{ env.VERSION }} .

    - name: Push Docker Image
      run: |
        docker push jsfrnc/devops-toolbox:${{ env.VERSION }}

    - name: Post Docker Image Digest as a GitHub Output
      id: image_digest
      run: |
        digest=$(docker inspect --format='{{index .RepoDigests 0}}' jsfrnc/devops-toolbox:${{ env.VERSION }})
        echo "digest=${digest}" >> $GITHUB_ENV
